# Generated by Django 5.2.12 on 2026-03-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_barstocksheet_sales_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barstocksheet',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='barstocksheet',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='barstocksheet',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
