# Generated by Django 5.2.12 on 2026-03-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_barstocksheet_cost_alter_barstocksheet_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barstocksheet',
            old_name='cost',
            new_name='unit_cost',
        ),
    ]
