# Generated by Django 5.2.12 on 2026-03-25 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_cost_barstocksheet_unit_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='LNKStockSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('opening_stock', models.IntegerField(blank=True, null=True)),
                ('add', models.IntegerField(blank=True, default=0, null=True)),
                ('total', models.IntegerField(blank=True, editable=False, null=True)),
                ('closing_stock', models.IntegerField(blank=True, editable=False, null=True)),
                ('sold', models.IntegerField(default=0)),
                ('rate', models.FloatField(default=0.0)),
                ('amount', models.FloatField(blank=True, editable=False, null=True)),
                ('unit_cost', models.FloatField(default=0.0)),
                ('sales_cost', models.FloatField(blank=True, editable=False, null=True)),
                ('profit', models.FloatField(blank=True, editable=False, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('item', 'date')},
            },
        ),
    ]
