# Generated by Django 5.2.12 on 2026-03-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_kitchenstocksheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchenstocksheet',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='kitchenstocksheet',
            name='unit_cost',
        ),
    ]
