# Generated by Django 5.2.12 on 2026-03-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_lnkstocksheet_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barstocksheet',
            name='department',
            field=models.CharField(choices=[('bar', 'Bar')], default='bar', max_length=20),
        ),
    ]
