# Generated by Django 5.2.12 on 2026-03-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_barstocksheet_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='barstocksheet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
