# Generated by Django 5.2.12 on 2026-03-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_barstocksheet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenstocksheet',
            name='department',
            field=models.CharField(choices=[('kitchen', 'Kitchen')], default='kitchen', max_length=20),
        ),
        migrations.AddField(
            model_name='kitchenstocksheet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='lnkstocksheet',
            name='department',
            field=models.CharField(choices=[('lnk', 'Kitchen')], default='lnk', max_length=20),
        ),
        migrations.AddField(
            model_name='lnkstocksheet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
