# Generated by Django 5.2.12 on 2026-04-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_sale_department_alter_lnkstocksheet_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='department',
            field=models.CharField(choices=[('bar', 'Bar'), ('lnk', 'LNK'), ('kitchen', 'Kitchen'), ('rooms', 'Rooms')], default='bar', max_length=20),
        ),
    ]
