# Generated by Django 5.2.12 on 2026-03-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, choices=[('kisumu', 'Kisumu'), ('kamamega', 'Kamamega')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('shop attendant', 'Shop Attendant'), ('supervisor', 'Supervisor'), ('weighter', 'Weighter')], max_length=20),
        ),
    ]
