# Generated by Django 5.2.12 on 2026-03-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_location_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('bar', 'Bar'), ('kitchen', 'Kitchen'), ('rooms', 'Rooms'), ('all', 'All')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, choices=[('kisumu', 'Kisumu'), ('kamamega', 'Kamamega'), ('all', 'All')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('shop attendant', 'Shop Attendant'), ('supervisor', 'Supervisor'), ('weighter', 'Weighter'), ('chef', 'Chef')], max_length=20),
        ),
    ]
