# Generated by Django 4.2.29 on 2026-04-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_department_alter_user_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('shop attendant', 'Shop Attendant'), ('supervisor', 'Supervisor'), ('waiter', 'waiter'), ('chef', 'Chef')], max_length=20),
        ),
    ]
