# Generated by Django 5.2.12 on 2026-04-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_department_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('bar', 'Bar'), ('shop attendant', 'Shop Attendant'), ('kitchen', 'Kitchen'), ('rooms', 'Rooms'), ('all', 'All')], max_length=20, null=True),
        ),
    ]
