# Generated by Django 4.2.29 on 2026-04-02 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_role'),
        ('user', '0006_alter_user_department_alter_user_role'),
    ]

    operations = [
    ]
