# Generated by Django 5.2.12 on 2026-04-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('bar', 'Bar'), ('lnk', 'LNK'), ('kitchen', 'Kitchen'), ('rooms', 'Rooms'), ('all', 'All')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('shop attendant', 'Shop Attendant'), ('waiter', 'waiter'), ('chef', 'Chef')], max_length=20),
        ),
    ]
