# Generated by Django 5.2.12 on 2026-03-25 12:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('beer', 'Beer'), ('whisky', 'Whisky'), ('wine', 'Wine'), ('vodka', 'Vodka'), ('rum', 'Rum'), ('tequila', 'Tequila'), ('gin', 'Gin'), ('non-alcoholic', 'Non-Alcoholic'), ('food', 'Food')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('department', models.CharField(choices=[('lnk', 'LNK'), ('bar', 'Bar'), ('kitchen', 'Kitchen'), ('rooms', 'Rooms'), ('all', 'All')], default='kitchen', max_length=20)),
                ('location', models.CharField(choices=[('kisumu', 'Kisumu'), ('kakamega', 'Kakamega'), ('all', 'All')], default='kisumu', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(choices=[('101', '101'), ('102', '102'), ('103', '103'), ('104', '104'), ('105', '105'), ('201', '201'), ('202', '202'), ('203', '203'), ('204', '204'), ('205', '205')], max_length=10)),
                ('room_type', models.CharField(choices=[('delux', 'Deluxe'), ('standard', 'Standard'), ('double', 'Double')], max_length=50)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('service', models.CharField(blank=True, choices=[('rooms', 'Rooms'), ('bar', 'Bar'), ('conference', 'Conference'), ('roof_top', 'Roof Top'), ('office_delivery', 'Office Delivery')], max_length=20, null=True)),
                ('room_type', models.CharField(blank=True, choices=[('deluxe', 'Deluxe Room'), ('double', 'Double Room'), ('standard', 'Standard Room')], max_length=20, null=True)),
                ('room_number', models.CharField(blank=True, max_length=10, null=True)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BarStockSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('beer', 'Beers'), ('cans', 'Cans'), ('whiskeys', 'Whiskeys'), ('brandies', 'Brandies'), ('vodka', 'Vodka'), ('gin', 'Gin'), ('rum', 'Rum'), ('liquers', 'Liquers'), ('wines', 'Wines'), ('soft drinks', 'Soft Drinks'), ('shots/tots', 'Shots/Tots'), ('ciders/others', 'Ciders/Others')], max_length=50)),
                ('opening_stock', models.IntegerField(blank=True, null=True)),
                ('add', models.IntegerField(blank=True, default=0, null=True)),
                ('total', models.IntegerField(blank=True, editable=False, null=True)),
                ('closing_stock', models.IntegerField(blank=True, editable=False, null=True)),
                ('sold', models.IntegerField()),
                ('rate', models.FloatField()),
                ('amount', models.FloatField(blank=True, editable=False, null=True)),
                ('cost', models.FloatField()),
                ('profit', models.FloatField(blank=True, editable=False, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('item', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.sale')),
            ],
        ),
    ]
