# Generated by Django 5.2.12 on 2026-03-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barstocksheet',
            name='sales_cost',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
