# Generated by Django 5.2.12 on 2026-03-25 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_kitchenstocksheet_profit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lnkstocksheet',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='lnkstocksheet',
            name='unit_cost',
        ),
    ]
