# Generated by Django 5.2.12 on 2026-04-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='department',
            field=models.CharField(choices=[('bar', 'Bar'), ('lnk', 'LNK'), ('kitchen', 'Kitchen'), ('rooms', 'Rooms')], default='bar', max_length=20),
        ),
        migrations.AlterField(
            model_name='lnkstocksheet',
            name='department',
            field=models.CharField(choices=[('lnk', 'LNK')], default='lnk', max_length=20),
        ),
    ]
